apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: mavenwebapprs
  namespace: test-ns
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: mavenwebapp
#    matchExpression: #Set(Expression) bases selectors
#    - key: app 
#      operator: in
#      values:
#      - "mavenwebapp"
#      - "maven"
  template:
    metadata:
      name: mavenwebapp
      labels:
        app: mavenwebapp
    spec: 
      containers:
      - name: mavenwebapp
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: mavenwebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports: 
  - port: 80
